# docker-compose.yml
version: "3"
services:
  backend:
    build: ./backend
    image: nuorisopalaute/service:v1
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app/
    command: sh -c "yarn install && yarn run watch-server"

  frontend:
    build: ./frontend
    image: tzaeru/nuorisopalaute-frontend:v1
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app/
    command: sh -c "yarn install && yarn run start"

  postgres:
    #ports:
    #  - 5432:5432
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
