---

name: Build
on: [push]

env:
  AWS_REGION: eu-west-1
  NODE_VERSION: "16"
  DOCKER_IMAGE_NAME: nuorisopalaute/service
  PROJECT: nuorisopalaute/frontend

permissions:
  id-token: write
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: espoon-voltti/voltti-actions/yarn@master
        with:
          node_version: "${{ env.NODE_VERSION }}"
          VERDACCIO_TOKEN: "${{ secrets.VERDACCIO_TOKEN }}"
          command: yarn test
          path: backend

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: espoon-voltti/voltti-actions/yarn@master
        with:
          node_version: "${{ env.NODE_VERSION }}"
          VERDACCIO_TOKEN: "${{ secrets.VERDACCIO_TOKEN }}"
          command: yarn test
          path: frontend

  frontend:
    needs:
      - test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: espoon-voltti/voltti-actions/yarn@master
        with:
          node_version: "${{ env.NODE_VERSION }}"
          VERDACCIO_TOKEN: "${{ secrets.VERDACCIO_TOKEN }}"
          command: yarn build
          path: frontend

      - name: Upload build
        uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: build
          path: frontend/build/
          retention-days: 3
    outputs:
      run_id: ${{ github.run_id }}

  backend:
    needs:
      - test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: espoon-voltti/voltti-actions/docker-build@master
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE }}
          AWS_REGION: ${{ env.AWS_REGION }}
          name: ${{ env.DOCKER_IMAGE_NAME }}
          path: backend
          build-args: |
            build=${{ github.run_number }}
            commit=${{ github.sha }}

  deploy:
    needs:
      - backend
      - frontend
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: '${{ secrets.NUORISOPALAUTE_PAT }}'
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'espoon-voltti',
            repo: 'nuorisopalaute-infra',
            workflow_id: 'deploy.yml',
            ref: 'master',
            inputs: {
              version: '${{ github.sha }}',
              run_id: '${{ needs.frontend.outputs.run_id }}',
            },
          })
